'use strict';

export const BUILD_DIRECTORY_TREE = 'BUILD_DIRECTORY_TREE';
export const TOGGLE_FOLDER = 'TOGGLE_FOLDER';
export const TOGGLE_FILE = 'TOGGLE_FILE';

export const START_PROJECT_PARSING = 'START_PROJECT_PARSING';
export const START_FILE_PARSING = 'START_FILE_PARSING';
export const END_FILE_PARSING = 'END_FILE_PARSING';
export const ERROR_FILE_PARSING = 'ERROR_FILE_PARSING';
export const SET_FILE_FUNCTIONS = 'SET_FILE_FUNCTIONS';
export const END_PROJECT_PARSING = 'END_PROJECT_PARSING';

export const SCAN_COMPLETED = 'SCAN_COMPLETED';
export const SEARCH_FUNCTION = 'SEARCH_FUNCTION';
export const SHOW_PREVIEW = 'SHOW_PREVIEW';
export const CHANGE_ACTIVE_PROJECT = 'CHANGE_ACTIVE_PROJECT';
export const OPEN_NEW_PROJECT = 'OPEN_NEW_PROJECT';
export const CLOSE_PROJECT = 'CLOSE_PROJECT';
export const CHANGE_ACTIVE_VIEW = 'CHANGE_ACTIVE_VIEW';
export const CLOSE_VIEW_TAB = 'CLOSE_VIEW_TAB';
export const START_FUNCTION_NAVIGATION = 'START_FUNCTION_NAVIGATION';
export const OPEN_FUNCTION = 'OPEN_FUNCTION';
