'use strict';

export const SCAN_COMPLETED = 'SCAN_COMPLETED';
export const SEARCH_FUNCTION = 'SEARCH_FUNCTION';
export const SHOW_PREVIEW = 'SHOW_PREVIEW';
export const CHANGE_ACTIVE_PROJECT = 'CHANGE_ACTIVE_PROJECT';
export const OPEN_NEW_PROJECT = 'OPEN_NEW_PROJECT';
export const CLOSE_PROJECT = 'CLOSE_PROJECT';
export const CHANGE_ACTIVE_VIEW = 'CHANGE_ACTIVE_VIEW';
export const CLOSE_VIEW_TAB = 'CLOSE_VIEW_TAB';
export const START_FUNCTION_NAVIGATION = 'START_FUNCTION_NAVIGATION';
export const OPEN_FUNCTION = 'OPEN_FUNCTION';
